import type { Metadata } from "next";
import { Cormorant_Upright, Open_Sans, Inter } from "next/font/google";
import "./globals.css";

const cormorantUpright = Cormorant_Upright({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--CU",
});

const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--OS",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorantUpright.variable} ${openSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
